// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.2";

// src/lib/mcp/tools/get-my-membership.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-membership.ts
var get_my_membership_default = defineTool({
  name: "get_my_membership",
  title: "Get my membership",
  description: "Get the signed-in user's Stream Net Mirror membership status, name, email and signup date.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("subscribers").select("name, email, phone, status, created_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return {
        content: [
          {
            type: "text",
            text: "No membership found for this account. Complete a payment and create an account with the same email address."
          }
        ],
        structuredContent: { membership: null }
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { membership: data }
    };
  }
});

// src/lib/mcp/tools/list-my-payments.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.2";
var list_my_payments_default = defineTool2({
  name: "list_my_payments",
  title: "List my payments",
  description: "List the payments made with the signed-in user's email address, including amount, currency, status and date.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("payments").select(
      "id, amount, currency, country, status, provider, promo_code, discount_applied, provider_transaction_id, created_at"
    ).order("created_at", { ascending: false }).limit(50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const payments = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(payments) }],
      structuredContent: { payments, count: payments.length }
    };
  }
});

// src/lib/mcp/tools/list-my-support-tickets.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.2";
var list_my_support_tickets_default = defineTool3({
  name: "list_my_support_tickets",
  title: "List my support tickets",
  description: "List the signed-in user's support tickets with subject, status and creation date.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("support_tickets").select("id, subject, message, status, payment_ref, created_at, updated_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const tickets = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(tickets) }],
      structuredContent: { tickets, count: tickets.length }
    };
  }
});

// src/lib/mcp/tools/create-support-ticket.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z } from "npm:zod@^3.25.76";
var create_support_ticket_default = defineTool4({
  name: "create_support_ticket",
  title: "Create support ticket",
  description: "Open a new support ticket for the signed-in user.",
  inputSchema: {
    subject: z.string().trim().describe("Short summary of the issue."),
    message: z.string().trim().describe("Full description of the issue."),
    payment_ref: z.string().trim().optional().describe("Optional payment reference or transaction id related to the issue.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ subject, message, payment_ref }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!subject || !message) {
      return {
        content: [{ type: "text", text: "Both subject and message are required." }],
        isError: true
      };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("support_tickets").insert({
      user_id: ctx.getUserId(),
      subject: subject.slice(0, 200),
      message: message.slice(0, 5e3),
      payment_ref: payment_ref || null,
      guest_email: ctx.getUserEmail() ?? null
    }).select("id, subject, status, created_at").maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Ticket created: ${JSON.stringify(data)}` }],
      structuredContent: { ticket: data }
    };
  }
});

// src/lib/mcp/tools/get-streaming-links.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@2.0.2";
var LINK_KEYS = ["streaming_link_1", "streaming_link_2", "streaming_link_3", "apk_download_link"];
var get_streaming_links_default = defineTool5({
  name: "get_streaming_links",
  title: "Get streaming links",
  description: "Get the current official Stream Net Mirror streaming website links and the Android APK download link.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("app_settings").select("key, value");
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const links = {};
    for (const row of data ?? []) {
      if (LINK_KEYS.includes(row.key)) links[row.key] = row.value;
    }
    return {
      content: [{ type: "text", text: JSON.stringify(links) }],
      structuredContent: { links }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rhobeyejmrnnreepacmr";
var mcp_default = defineMcp({
  name: "stream-net-mirror",
  title: "Stream Net Mirror",
  version: "0.1.0",
  instructions: "Tools for Stream Net Mirror members. Check membership status, review payments, read and open support tickets, and fetch the current official streaming and APK download links. All tools act as the signed-in member.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_membership_default,
    list_my_payments_default,
    list_my_support_tickets_default,
    create_support_ticket_default,
    get_streaming_links_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
